cities = [
    'natura-siberica-moskva-trts-metropolis', 
    ]


    # cities = [
    # 'natura-siberica-moskva-trts-metropolis', 
    # 'moskva-trts-okeaniya', 
    # 'ns-kaliningrad-evropa-g-kaliningrad-ul-teatralnaya-d-30', 
    # 'trk-brosko-moll',
    # 'vladivostok-tts-kalina-moll',
    # 'voronezh-tts-galereya-chizhova',
    # 'ekaterinburg',
    # 'kazan',
    # 'krasnodar',
    # 'kizil',
    # 'makhachkala',
    # 'avenue',
    # 'aviapark',
    # 'vegas-kuntsevo',
    # 'europeyskiy',
    # 'kaleydoskop',
    # 'columbus',
    # 'leninskiy-prospekt-119',
    # 'maroseyka',
    # 'mega-belaya-dacha',
    # 'nahimovskiy',
    # 'okhotniy-ryad',
    # 'pyatnitskaya',
    # 'raykin-plaza',
    # 'tverskaya-flagmanskiy-magazin',
    # 'hong-kong',
    # 'bosniya-i-gertsegovina-delta-planet',
    # 'tallinn',
    # 'podgorica',
    # 'budva',
    # 'belgrad-kralja-aleksandra-86',
    # 'belgrad-kralja-aleksandra-44',
    # 'belgrad-usce',
    # 'belgrad-kajmak%C4%8Dalanska',
    # 'barcelona-diagonal',
    # 'barcelona-santa-anna',
    # 'chelyabinsk',
    # 'ufa',
    # 'tumen',
    # 'sochi',
    # 'saratov',
    # 'nevskiy',
    # 'samara',
    # 'ryazan',
    # 'omsk',
    # 'novosibirsk-galereya',
    # 'novokuznetcsk',
    # 'nigniy-novgorod',
    # 'murmansk',
    # 'moskva-trts-khorosho',
    # 'festival',
    # 'tverskaya-27',
    # ]
base_url = 'https://naturasiberica.ru/our-shops/'
yml_path = "D:/WebScraping/third_web/t.yaml"
slash = ''
csv_path = 'D:/WebScraping/third_web/csv_third_web.json'